map $http_x_forwarded_proto $forwarded_proto_from_xfp {
    default $scheme;
    https https;
}

map $http_cf_visitor $forwarded_proto {
    default $forwarded_proto_from_xfp;
    ~*"scheme":"https" https;
}

map $forwarded_proto $forwarded_port {
    default $server_port;
    https 443;
}

server {
    listen 80;
    server_name _;

   location / {
       proxy_pass http://holosummary:8080;

    proxy_set_header X-Forwarded-Proto $forwarded_proto;
       proxy_set_header X-Forwarded-Host $host;
       proxy_set_header X-Forwarded-Port $forwarded_port;

       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   }
}