services:
  nginx:
    image: nginx:alpine
    container_name: holo-nginx
    environment:
      - SERVER_IP=${SERVER_IP}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - holo-summary
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: holo-summary-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - tunnel_net

  holo-summary:
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: ghcr.io/homulily85/holosummary:latest
    container_name: holo-summary
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/holo_summary
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TRANSCRIPTION_API_URL=http://transcript-crawler:8000/api/transcript
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  transcript-crawler:
    build:
      context: ./python-transcript-crawler
      dockerfile: Dockerfile
    container_name: transcript-crawler
    environment:
      - WINDOWS_TAILSCALE_IP=${WINDOWS_TAILSCALE_IP}
      - PROXY_PORT=${PROXY_PORT}
    image: ghcr.io/homulily85/transcript-crawler:latest
    restart: unless-stopped

  db:
    image: postgres:17.9
    container_name: holo-summary-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: holo_summary
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d holo_summary"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  tunnel_net:
    driver: bridge

volumes:
  postgres-data: