spring.application.name=HoloSummary
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
holodex-videos-api-client.url=https://holodex.net/api/v2/videos
holodex-videos-api-client.header.referer=https://holodex.net/
holodex-videos-api-client.header.user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36
holodex-videos-api-client.query.status=past,missing,live,upcoming
holodex-videos-api-client.query.paginated=false
holodex-videos-api-client.query.max_upcoming_hours=24
holodex-videos-api-client.query.org=Hololive
holodex-videos-api-client.query.type=stream
holodex-videos-api-client.query.limit=50
holodex-videos-api-client.query.offset=0
holodex-videos-api-client.query.include=mentions
transcription-api-client.url=${TRANSCRIPTION_API_URL}