spring.application.name=HoloSummary
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
holodex-videos-api-client.url=https://holodex.net/api/v2/videos
holodex-videos-api-client.header.referer=https://holodex.net/
holodex-videos-api-client.header.user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36
holodex-videos-api-client.query.status=past,missing,live,upcoming
holodex-videos-api-client.query.paginated=false
holodex-videos-api-client.query.max_upcoming_hours=24
holodex-videos-api-client.query.org=Hololive
holodex-videos-api-client.query.type=stream
holodex-videos-api-client.query.limit=50
holodex-videos-api-client.query.offset=0
holodex-videos-api-client.query.include=mentions
transcription-api-client.url=${TRANSCRIPTION_API_URL}
open-router-api-client.url=https://openrouter.ai/api/v1/chat/completions
open-router-api-client.header.authorization=Bearer ${OPEN_ROUTER_API_KEY}
open-router-api-client.body.model=deepseek/deepseek-v4-flash
open-router-api-client.body.system-prompt=You are an expert summarizer processing a YouTube video transcript.\nYour goal is to identify distinct topics and summarize each proportionally based on its complexity and duration in the video.\n\nYou will receive a JSON payload in the exact format shown below:\n\n```json\n{\n  \"text\": \"The transcript taken from the video that you need to summarize.\",\n  \"speakerName\": [\"An array of strings containing the names of the main speakers in the video.\"]\n}\n\n```\n\n**Output Format:**\nYou MUST return ONLY a text with structure like below\n\nTopic 1 title. Summarized content of topic 1.\n\nTopic 2 title. Summarized content of topic 2.\n\n**Notes:**\n\n* You must write your summary in English only.\n* Avoid overusing generic terms such as \"Speaker\" and \"Host\" in your summary. Instead, flexibly alternate between using the speakers'\'' actual names and third-person pronouns (e.g., \"he,\" \"she,\" \"they\").